apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workloads-chaos 
  namespace: workloads
subjects:
- kind: ServiceAccount
  name: workloads-chaos 
  namespace: workloads-chaos 
roleRef:
  kind: Role
  name: workloads-chaos
  apiGroup: rbac.authorization.k8s.io
